server {
    listen 80;
    server_name CALI_LIMONAR_PPAL;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Siempre retorna 503 Service Unavailable
        return 503;
    }
    
    # Página de error personalizada
    error_page 503 /index.html;
    
    location = /index.html {
        root /usr/share/nginx/html;
        internal;
    }
}
